--- 
chdir: /home/ubuntu/apps/segmentupload/current
environment: production
address: 0.0.0.0
port: 80
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []

wait: 30
servers: 4
daemonize: true
